/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package c1_presentacion.form;

import c2_aplicacion.GestionarMarcaServicio;
import c3_dominio.entidad.Marca;
import java.util.List;
import javax.swing.table.TableColumn;
import mastersoft.modelo.ModeloTabla;
import mastersoft.tabladatos.Columna;
import mastersoft.tabladatos.Fila;
import mastersoft.tabladatos.Tabla;

/**
 *
 * @author Carlos Alfredo Osorio Perez <hacybeyker@hotmail.com>
 */
public class FormGestionarMarca extends javax.swing.JDialog {

    /**
     * Creates new form FormGestionarMarca
     */
    public FormGestionarMarca(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        crearTabla();
        buscarMarcas();
    }
    
    public void crearTabla(){
        Tabla tablaMarca = new Tabla();
        tablaMarca.agregarColumna(new Columna("Codigo", "java.lang.Integer"));
        tablaMarca.agregarColumna(new Columna("Nombre", "java.lang.String"));
        ModeloTabla modeloTabla = new ModeloTabla(tablaMarca);
        this.tablaMarca.setModel(modeloTabla);
        TableColumn columna0,columna1;
        columna0 = this.tablaMarca.getColumnModel().getColumn(0);
        this.tablaMarca.removeColumn(columna0);
        columna1 = this.tablaMarca.getColumnModel().getColumn(0);
        columna1.setPreferredWidth(350);
        columna1.setMaxWidth(400);
        columna1.setMinWidth(100);
    }
    
    public Marca buscarMarca(int codigo){
        return null;
    }
    
    public void buscarMarcas(){
        ModeloTabla modeloTabla = (ModeloTabla)this.tablaMarca.getModel();
        try {
            GestionarMarcaServicio gestionarMarcaServicio = new GestionarMarcaServicio();
            List<Marca> marcas = gestionarMarcaServicio.buscar();
            modeloTabla.eliminarTotalFilas();
            for (Marca marca : marcas) {
                Fila fila = new Fila();
                fila.agregarValorCelda(marca.getCodigo());
                fila.agregarValorCelda(marca.getNombre());
                modeloTabla.agregarFila(fila);
            }
            modeloTabla.refrescarDatos();
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
    }
    
    public void buscarPorNombre(String nombre){
        ModeloTabla modeloTabla = (ModeloTabla)this.tablaMarca.getModel();
        try {
            GestionarMarcaServicio gestionarMarcaServicio = new GestionarMarcaServicio();
            List<Marca> marcas = gestionarMarcaServicio.buscarPorNombre(nombre);
            modeloTabla.eliminarTotalFilas();
            for (Marca marca : marcas) {
                Fila fila = new Fila();
                fila.agregarValorCelda(marca.getCodigo());
                fila.agregarValorCelda(marca.getNombre());
                modeloTabla.agregarFila(fila);
            }
            modeloTabla.refrescarDatos();
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
    }
    
    public Marca buscarPorCodigo(int codigo){
        Marca marca = new Marca();
        try {
            GestionarMarcaServicio gestionarMarcaServicio = new GestionarMarcaServicio();
            marca = gestionarMarcaServicio.buscarPorCodigo(codigo);
        } catch (Exception e) {
        }
        return marca;
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BarraAC = new javax.swing.JToolBar();
        botonACCrear = new javax.swing.JToggleButton();
        botonACModificar = new javax.swing.JToggleButton();
        botonACEliminar = new javax.swing.JToggleButton();
        botonACSalir = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMarca = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        textoNombre = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestionar Marca");

        BarraAC.setRollover(true);

        botonACCrear.setText("Crear");
        botonACCrear.setFocusable(false);
        botonACCrear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonACCrear.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonACCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonACCrearActionPerformed(evt);
            }
        });
        BarraAC.add(botonACCrear);

        botonACModificar.setText("Modificar");
        botonACModificar.setFocusable(false);
        botonACModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonACModificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonACModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonACModificarActionPerformed(evt);
            }
        });
        BarraAC.add(botonACModificar);

        botonACEliminar.setText("Eliminar");
        botonACEliminar.setFocusable(false);
        botonACEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonACEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonACEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonACEliminarActionPerformed(evt);
            }
        });
        BarraAC.add(botonACEliminar);

        botonACSalir.setText("Salir");
        botonACSalir.setFocusable(false);
        botonACSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonACSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonACSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonACSalirActionPerformed(evt);
            }
        });
        BarraAC.add(botonACSalir);

        getContentPane().add(BarraAC, java.awt.BorderLayout.PAGE_START);

        tablaMarca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaMarca);

        jLabel1.setText("Nombre:");

        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(botonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonACCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonACCrearActionPerformed
        // TODO add your handling code here:
        new FormRegistrarMarca(this).setVisible(true);
        buscarMarcas();
    }//GEN-LAST:event_botonACCrearActionPerformed

    private void botonACModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonACModificarActionPerformed
        // TODO add your handling code here:
        buscarMarcas();
    }//GEN-LAST:event_botonACModificarActionPerformed

    private void botonACEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonACEliminarActionPerformed
        // TODO add your handling code here:
        buscarMarcas();
    }//GEN-LAST:event_botonACEliminarActionPerformed

    private void botonACSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonACSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_botonACSalirActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        // TODO add your handling code here:
        buscarPorNombre(textoNombre.getText().trim());
    }//GEN-LAST:event_botonBuscarActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar BarraAC;
    private javax.swing.JToggleButton botonACCrear;
    private javax.swing.JToggleButton botonACEliminar;
    private javax.swing.JToggleButton botonACModificar;
    private javax.swing.JToggleButton botonACSalir;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaMarca;
    private javax.swing.JTextField textoNombre;
    // End of variables declaration//GEN-END:variables
}
